import type { ConfidenceLevel, Modality, ObservationSource, ObservationStatus } from '@/domain';

/**
 * The 20 records of the `Dummy Installed Base` sheet in the official challenge workbook
 * `Dummy_Installed_Base_Hackathon.xlsx`, transcribed verbatim.
 *
 * The workbook's own README sheet states these rows are "to use as expected output / database
 * seed". They are transcribed as a static typed table rather than parsed at runtime: the data
 * never changes, and a spreadsheet parser would add a dependency and a parsing surface for
 * nothing.
 *
 * Every value below is copied from the sheet. Nothing is inferred, completed or normalized here;
 * the mapping onto the domain model happens in `development-seed.ts`. See
 * [DECISIONS.md](../../../docs/DECISIONS.md) decisions 9 and 15 for what that mapping may do.
 */
export interface OfficialInstalledBaseRecord {
  /** Column A. 1 to 20, the workbook's own row identity. */
  readonly observationId: number;
  /** Column B. */
  readonly country: string;
  /** Column C. */
  readonly city: string;
  /** Column D. */
  readonly customer: string;
  /** Column E. */
  readonly observer: string;
  /** Column F, a calendar date with no time of day. */
  readonly visitDate: string;
  /** Column G. Every official value is already in the closed modality vocabulary. */
  readonly modality: Modality;
  /** Column H. */
  readonly quantity: number;
  /** Column I, one of the six fictional brands on the `Dummy Reference Lists` sheet. */
  readonly brand: string;
  /** Column J. Present on all 20 rows. */
  readonly model: string;
  /** Column K, a bare integer. Never treated as an exact age; see decision 15. */
  readonly approximateAgeYears: number;
  /** Column L. Equals the visit year minus the approximate age on all 20 rows. */
  readonly estimatedInstallationYear: number;
  /** Column M. */
  readonly confidence: ConfidenceLevel;
  /** Column N. */
  readonly status: ObservationStatus;
  /** Column O. `Voice` on all 20 rows. */
  readonly source: ObservationSource;
  /** Column P. Both rows of a session share it when the visit produced one utterance. */
  readonly voiceInput: string;
  /** Column Q. */
  readonly followUpQuestion: string;
  /** Column R. */
  readonly followUpAnswer: string;
  /** Column S. */
  readonly notes: string;
}

export const OFFICIAL_INSTALLED_BASE_RECORDS: readonly OfficialInstalledBaseRecord[] = [
  {
    observationId: 1,
    country: 'Panama',
    city: 'Panama City',
    customer: 'Hospital DemoCare Pacific',
    observer: 'Field User 01',
    visitDate: '2026-08-18',
    modality: 'MR',
    quantity: 2,
    brand: 'NovaMed',
    model: 'NM-MR 700',
    approximateAgeYears: 7,
    estimatedInstallationYear: 2019,
    confidence: 'High',
    status: 'Reported',
    source: 'Voice',
    voiceInput: 'I am at Hospital DemoCare Pacific in Panama. They have two MR systems and one CT.',
    followUpQuestion: 'Do you know the brand of the MR systems?',
    followUpAnswer: 'Yes, NovaMed.',
    notes: 'Two MR systems observed in imaging area.',
  },
  {
    observationId: 2,
    country: 'Panama',
    city: 'Panama City',
    customer: 'Hospital DemoCare Pacific',
    observer: 'Field User 01',
    visitDate: '2026-08-18',
    modality: 'CT',
    quantity: 1,
    brand: 'Aurelia Health',
    model: 'AH-CT 320',
    approximateAgeYears: 5,
    estimatedInstallationYear: 2021,
    confidence: 'High',
    status: 'Reported',
    source: 'Voice',
    voiceInput: 'I am at Hospital DemoCare Pacific in Panama. They have two MR systems and one CT.',
    followUpQuestion: 'Do you know the brand and approximate age of the CT?',
    followUpAnswer: 'Aurelia Health, around 5 years old.',
    notes: 'Single CT system observed.',
  },
  {
    observationId: 3,
    country: 'Brazil',
    city: 'Sao Paulo',
    customer: 'Hospital DemoCare Horizon',
    observer: 'Sales User 02',
    visitDate: '2026-08-16',
    modality: 'MR',
    quantity: 3,
    brand: 'BluePeak Medical',
    model: 'BP-MR 500',
    approximateAgeYears: 9,
    estimatedInstallationYear: 2017,
    confidence: 'Medium',
    status: 'Estimated',
    source: 'Voice',
    voiceInput:
      'Hospital DemoCare Horizon has three MR systems. Two look older and one seems newer.',
    followUpQuestion: 'Can you estimate the age of each system?',
    followUpAnswer: 'Two are around 9 years old and one around 3 years.',
    notes: 'Aggregate row for older systems.',
  },
  {
    observationId: 4,
    country: 'Brazil',
    city: 'Sao Paulo',
    customer: 'Hospital DemoCare Horizon',
    observer: 'Sales User 02',
    visitDate: '2026-08-16',
    modality: 'MR',
    quantity: 1,
    brand: 'BluePeak Medical',
    model: 'BP-MR 900',
    approximateAgeYears: 3,
    estimatedInstallationYear: 2023,
    confidence: 'Medium',
    status: 'Estimated',
    source: 'Voice',
    voiceInput:
      'Hospital DemoCare Horizon has three MR systems. Two look older and one seems newer.',
    followUpQuestion: 'Do you know whether the newer system is the same brand?',
    followUpAnswer: 'Yes, same brand, different model.',
    notes: 'Newer MR system.',
  },
  {
    observationId: 5,
    country: 'Brazil',
    city: 'Campinas',
    customer: 'Clinica DemoCare Light',
    observer: 'Field User 03',
    visitDate: '2026-08-15',
    modality: 'CT',
    quantity: 2,
    brand: 'Orion Imaging',
    model: 'OI-CT 450',
    approximateAgeYears: 11,
    estimatedInstallationYear: 2015,
    confidence: 'High',
    status: 'Reported',
    source: 'Voice',
    voiceInput: 'At Clinica DemoCare Light I saw two CT scanners.',
    followUpQuestion: 'Do you know the brand and approximate age?',
    followUpAnswer: 'Orion Imaging, about 11 years.',
    notes: 'Potential aging installed base.',
  },
  {
    observationId: 6,
    country: 'Brazil',
    city: 'Campinas',
    customer: 'Clinica DemoCare Light',
    observer: 'Field User 03',
    visitDate: '2026-08-15',
    modality: 'Ultrasound',
    quantity: 5,
    brand: 'HelixCare',
    model: 'HC-US 40',
    approximateAgeYears: 4,
    estimatedInstallationYear: 2022,
    confidence: 'Medium',
    status: 'Reported',
    source: 'Voice',
    voiceInput: 'They also have about five ultrasound systems.',
    followUpQuestion: 'Are all five from the same brand?',
    followUpAnswer: 'I think four are HelixCare; one is unknown.',
    notes: 'Four confirmed, one uncertain.',
  },
  {
    observationId: 7,
    country: 'Mexico',
    city: 'Mexico City',
    customer: 'Centro Medico DemoCare Valley',
    observer: 'Account User 04',
    visitDate: '2026-08-14',
    modality: 'MR',
    quantity: 1,
    brand: 'Zenith MedTech',
    model: 'ZM-MR 810',
    approximateAgeYears: 6,
    estimatedInstallationYear: 2020,
    confidence: 'High',
    status: 'Reported',
    source: 'Voice',
    voiceInput: 'Centro Medico DemoCare Valley has one MR, two CTs and several ultrasound systems.',
    followUpQuestion: 'Do you know the MR brand?',
    followUpAnswer: 'Zenith MedTech, around six years old.',
    notes: 'MR observation.',
  },
  {
    observationId: 8,
    country: 'Mexico',
    city: 'Mexico City',
    customer: 'Centro Medico DemoCare Valley',
    observer: 'Account User 04',
    visitDate: '2026-08-14',
    modality: 'CT',
    quantity: 2,
    brand: 'Aurelia Health',
    model: 'AH-CT 510',
    approximateAgeYears: 8,
    estimatedInstallationYear: 2018,
    confidence: 'Medium',
    status: 'Estimated',
    source: 'Voice',
    voiceInput: 'Centro Medico DemoCare Valley has one MR, two CTs and several ultrasound systems.',
    followUpQuestion: 'Can you estimate the CT age?',
    followUpAnswer: 'Around eight years, both similar.',
    notes: 'Two similar CT units.',
  },
  {
    observationId: 9,
    country: 'Mexico',
    city: 'Monterrey',
    customer: 'Hospital DemoCare North',
    observer: 'Field User 05',
    visitDate: '2026-08-13',
    modality: 'Ultrasound',
    quantity: 6,
    brand: 'NovaMed',
    model: 'NM-US 55',
    approximateAgeYears: 2,
    estimatedInstallationYear: 2024,
    confidence: 'High',
    status: 'Reported',
    source: 'Voice',
    voiceInput: 'Hospital DemoCare North has six ultrasound units, mostly new.',
    followUpQuestion: 'Do you know the brand and how new they are?',
    followUpAnswer: 'NovaMed, roughly two years old.',
    notes: 'Recent installation.',
  },
  {
    observationId: 10,
    country: 'Chile',
    city: 'Santiago',
    customer: 'Clinica DemoCare Andes',
    observer: 'Sales User 06',
    visitDate: '2026-08-12',
    modality: 'CT',
    quantity: 1,
    brand: 'BluePeak Medical',
    model: 'BP-CT 610',
    approximateAgeYears: 13,
    estimatedInstallationYear: 2013,
    confidence: 'Medium',
    status: 'Estimated',
    source: 'Voice',
    voiceInput: 'At Clinica DemoCare Andes there is one older CT system.',
    followUpQuestion: 'Can you estimate how old it is?',
    followUpAnswer: 'Maybe around thirteen years.',
    notes: 'Old CT estimate.',
  },
  {
    observationId: 11,
    country: 'Chile',
    city: 'Santiago',
    customer: 'Clinica DemoCare Andes',
    observer: 'Sales User 06',
    visitDate: '2026-08-12',
    modality: 'MR',
    quantity: 2,
    brand: 'Orion Imaging',
    model: 'OI-MR 620',
    approximateAgeYears: 5,
    estimatedInstallationYear: 2021,
    confidence: 'High',
    status: 'Reported',
    source: 'Voice',
    voiceInput: 'They also have two MR systems from the same manufacturer.',
    followUpQuestion: 'Do you know the brand and approximate age?',
    followUpAnswer: 'Orion Imaging, about five years.',
    notes: 'Two MR units.',
  },
  {
    observationId: 12,
    country: 'Argentina',
    city: 'Buenos Aires',
    customer: 'Hospital DemoCare Park',
    observer: 'Field User 07',
    visitDate: '2026-08-11',
    modality: 'MR',
    quantity: 1,
    brand: 'HelixCare',
    model: 'HC-MR 300',
    approximateAgeYears: 10,
    estimatedInstallationYear: 2016,
    confidence: 'Medium',
    status: 'Reported',
    source: 'Voice',
    voiceInput: 'Hospital DemoCare Park has one MR that looks around ten years old.',
    followUpQuestion: 'Do you know the brand or model?',
    followUpAnswer: 'HelixCare, model unknown.',
    notes: 'Model not visible.',
  },
  {
    observationId: 13,
    country: 'Argentina',
    city: 'Buenos Aires',
    customer: 'Hospital DemoCare Park',
    observer: 'Field User 07',
    visitDate: '2026-08-11',
    modality: 'CT',
    quantity: 3,
    brand: 'Zenith MedTech',
    model: 'ZM-CT 430',
    approximateAgeYears: 7,
    estimatedInstallationYear: 2019,
    confidence: 'High',
    status: 'Reported',
    source: 'Voice',
    voiceInput: 'I also counted three CT scanners.',
    followUpQuestion: 'Are they all the same brand?',
    followUpAnswer: 'Yes, all Zenith MedTech.',
    notes: 'Three CT units.',
  },
  {
    observationId: 14,
    country: 'Colombia',
    city: 'Bogota',
    customer: 'Clinica DemoCare Central',
    observer: 'Account User 08',
    visitDate: '2026-08-10',
    modality: 'Ultrasound',
    quantity: 8,
    brand: 'Aurelia Health',
    model: 'AH-US 70',
    approximateAgeYears: 6,
    estimatedInstallationYear: 2020,
    confidence: 'Medium',
    status: 'Estimated',
    source: 'Voice',
    voiceInput: 'Clinica DemoCare Central has many ultrasound systems, maybe eight.',
    followUpQuestion: 'Do you know the brand and whether eight is confirmed?',
    followUpAnswer: 'Aurelia Health. Eight is my best estimate.',
    notes: 'Quantity estimated.',
  },
  {
    observationId: 15,
    country: 'Colombia',
    city: 'Medellin',
    customer: 'Hospital DemoCare Pines',
    observer: 'Field User 09',
    visitDate: '2026-08-09',
    modality: 'MR',
    quantity: 2,
    brand: 'NovaMed',
    model: 'NM-MR 720',
    approximateAgeYears: 4,
    estimatedInstallationYear: 2022,
    confidence: 'High',
    status: 'Reported',
    source: 'Voice',
    voiceInput: 'Hospital DemoCare Pines has two MR systems.',
    followUpQuestion: 'Do you know their approximate age?',
    followUpAnswer: 'Around four years.',
    notes: 'Two MR systems.',
  },
  {
    observationId: 16,
    country: 'Peru',
    city: 'Lima',
    customer: 'Instituto DemoCare Lima',
    observer: 'Sales User 10',
    visitDate: '2026-08-08',
    modality: 'CT',
    quantity: 2,
    brand: 'Orion Imaging',
    model: 'OI-CT 540',
    approximateAgeYears: 12,
    estimatedInstallationYear: 2014,
    confidence: 'Medium',
    status: 'Estimated',
    source: 'Voice',
    voiceInput: 'Instituto DemoCare Lima has two CT systems, both quite old.',
    followUpQuestion: 'How old would you estimate them to be?',
    followUpAnswer: 'Around twelve years.',
    notes: 'Potential refresh opportunity.',
  },
  {
    observationId: 17,
    country: 'Peru',
    city: 'Lima',
    customer: 'Instituto DemoCare Lima',
    observer: 'Sales User 10',
    visitDate: '2026-08-08',
    modality: 'MR',
    quantity: 1,
    brand: 'BluePeak Medical',
    model: 'BP-MR 840',
    approximateAgeYears: 2,
    estimatedInstallationYear: 2024,
    confidence: 'High',
    status: 'Reported',
    source: 'Voice',
    voiceInput: 'They recently added one MR.',
    followUpQuestion: 'Do you know the brand and installation timeframe?',
    followUpAnswer: 'BluePeak Medical, installed about two years ago.',
    notes: 'Recent MR.',
  },
  {
    observationId: 18,
    country: 'Costa Rica',
    city: 'San Jose',
    customer: 'Hospital DemoCare Green',
    observer: 'Field User 11',
    visitDate: '2026-08-07',
    modality: 'Ultrasound',
    quantity: 4,
    brand: 'HelixCare',
    model: 'HC-US 60',
    approximateAgeYears: 9,
    estimatedInstallationYear: 2017,
    confidence: 'Medium',
    status: 'Reported',
    source: 'Voice',
    voiceInput: 'Hospital DemoCare Green has four ultrasound systems, all the same family.',
    followUpQuestion: 'Can you estimate the age?',
    followUpAnswer: 'Around nine years.',
    notes: 'Same family.',
  },
  {
    observationId: 19,
    country: 'Dominican Republic',
    city: 'Santo Domingo',
    customer: 'Centro Diagnostico DemoCare Caribbean',
    observer: 'Account User 12',
    visitDate: '2026-08-06',
    modality: 'CT',
    quantity: 1,
    brand: 'Zenith MedTech',
    model: 'ZM-CT 760',
    approximateAgeYears: 3,
    estimatedInstallationYear: 2023,
    confidence: 'High',
    status: 'Reported',
    source: 'Voice',
    voiceInput: 'Centro Diagnostico DemoCare Caribbean has one CT, relatively new.',
    followUpQuestion: 'Do you know the brand and approximate age?',
    followUpAnswer: 'Zenith MedTech, around three years.',
    notes: 'Newer CT.',
  },
  {
    observationId: 20,
    country: 'Ecuador',
    city: 'Quito',
    customer: 'Hospital DemoCare Metro North',
    observer: 'Field User 13',
    visitDate: '2026-08-05',
    modality: 'MR',
    quantity: 2,
    brand: 'Aurelia Health',
    model: 'AH-MR 650',
    approximateAgeYears: 8,
    estimatedInstallationYear: 2018,
    confidence: 'Medium',
    status: 'Estimated',
    source: 'Voice',
    voiceInput: 'Hospital DemoCare Metro North has two MR systems. I could not see the model.',
    followUpQuestion: 'Do you know the brand and approximate age?',
    followUpAnswer: 'Aurelia Health, maybe eight years.',
    notes: 'Model unknown.',
  },
];
